### ISSUE TITLE
tag a first version?

### ISSUE THREAD

**Issue by pdaures** [mavlink/MAVSDK-Proto#108]
Hi,
I was curious about mavlink and MAVSDK.
I was wondering how hard it is to work without a versioned proto definition? I see different projects depends on different commit hashes of MAVSDK-Proto.

What's missing before we could have a v0.0.1 ?
Thanks!

**Comment by JonasVautherin** [comment]
The idea is that you can extend the proto files without breaking compatibility. So there is no need to version them, I think. Because we rely on gRPC, it is a client-server design.

If `mavsdk_server` has a version of the proto file more recent than the client (e.g. MAVSDK-Python), then it's alright. If `mavsdk_server` is older than the client, then it could happen that when you call a function, you receive an "UNIMPLEMENTED" error. Which is not ideal, but it is not too bad. We usually try to not get into this situation by adding the features in `mavsdk_server` first.

Now, it could still happen that we change the proto files in a way that would break backward compatibility, and that's why the different projects are labeled `0.x.x` (e.g. `mavsdk_server` is `v0.20.0`, MAVSDK-Python is `0.3.0`). Once we move to `1.x.x`, it will mean that our API is stable and that we won't break it anymore. It doesn't mean that we keep breaking it right now: it is actually quite stable. But some things may be renamed before we move to `1.x.x`.

Does that make sense?

**Comment by JonasVautherin** [comment]
More specifically, you will find the versioned released in the different repos:

- [MAVSDK](https://github.com/mavlink/mavsdk/releases): v0.20.0
- [MAVSDK-Swift](https://github.com/mavlink/mavsdk-swift/releases): 0.6.0
- [MAVSDK-Python](https://github.com/mavlink/MAVSDK-Python/releases): 0.3.0
- [MAVSDK-Java](https://github.com/mavlink/MAVSDK-Java/releases): 0.2.0

[MAVSDK-CSharp](https://github.com/mavlink/MAVSDK-CSharp/) and [MAVSDK-JavaScript](https://github.com/mavlink/MAVSDK-JavaScript/) are still prototypes and therefore not released yet.
