### ISSUE TITLE
Camera: need a way to manage media

### ISSUE THREAD

**Issue by JonasVautherin** [mavlink/MAVSDK-Proto#21]
[SubscribeCameraInfo](https://github.com/dronecore/DroneCore-Proto/blob/master/camera/camera.proto#L20) will receive the `CaptureInfo` of the next pictures that are taken, but what about the previous ones? Would there be a way in the camera plugin to list the files present on the camera?

What about videos present on the camera?

@thomasgubler @julianoes FYI, creating the issue to keep a trace.

**Comment by JonasVautherin** [comment]
Does that mean that if I make a video, there is no way to download it on my app?

And if I lose the connection to the drone for a while during the mission and miss some `CameraInfo` callabacks, then I won't know how many pictures have been taken unless I do some guessing on the client side, right?

**Comment by hamishwillee** [comment]
Yes, well to be precise there is now way to do it via the MAVLink API. All that does is give you a download URL when each photo is taken. 

In many cases that is probably fine - you just pull the memory card and inspect after landing. It does seem like an unnecessary limitation though. Lets discuss a revision if this is a use case we want.

@dogmaphobic and @lbegani probably good people to talk to in first instance.

**Comment by dogmaphobic** [comment]
Until now, this was never needed. That's why it doesn't exist. With that said, it wouldn't take much to add a new set of MAVLink messages to request a list of stored media (along with their URIs).

For what's worth, in my code, when you "take a picture" or when you "record a video", I do the same locally. I capture a frame off the video stream for when taking photos and I record the stream when recording videos. That gives me a copy of everything the camera is doing. This allows for a quick review of photos and videos, albeit at a much lower resolution (video stream resolution). That's because there isn't really enough bandwidth for a full download of all media straight off the camera. Of course this is all for "manually" triggered photo/video. If the capture is a result of a mission, I don't save anything and we're on the same boat.

**Comment by JonasVautherin** [comment]
@dogmaphobic: thanks, that's helping

@thomasgubler: FYI. I'll wait for your insights about this requirement.

**Comment by hamishwillee** [comment]
@dogmaphobic 

> Until now, this was never needed. That's why it doesn't exist. With that said, it wouldn't take much to add a new set of MAVLink messages to request a list of stored media (along with their URIs).

Should this perhaps be a generic File management API - ie not Camera specific?

**Comment by dogmaphobic** [comment]
There is already, if I'm not mistaken, an FTP type protocol. That sort of protocol however, implies iterating through directories and listing its files and subdirectories. For cameras, it may make more sense to have something specific: Give me a list of photos/videos and be done with it.

**Comment by JonasVautherin** [comment]
> There is already, if I'm not mistaken, an FTP type protocol.

Are you referring to PTP (on which MTP is based, by the way)?

**Comment by coderkalyan** [comment]
@JonasVautherin MAVLink does have an FTP type protocol, see here: https://mavlink.io/en/services/ftp.html. I think this is what @dogmaphobic is referring to

**Comment by julianoes** [comment]
MAVLink FTP was added to proto in #142.
