### ISSUE TITLE
Design camera server implement discussion

### ISSUE THREAD

**Issue by tbago** [mavlink/MAVSDK-Proto#316]
When check the **camera.proto** and **camera_server.proto**,  I found something need a discussion.

1. The camera.proto and camera_server.proto have some same definition (e.g. [Position in client](https://github.com/mavlink/MAVSDK-Proto/blob/82e8540f980ea318447f79f4cba8813993ae2a6b/protos/camera_server/camera_server.proto#L79) [Position in server](https://github.com/mavlink/MAVSDK-Proto/blob/82e8540f980ea318447f79f4cba8813993ae2a6b/protos/camera_server/camera_server.proto#L79) ). Maybe better define in the camera_common.proto. The camera_server.proto also need to add [camera_mode](https://github.com/mavlink/MAVSDK-Proto/blob/82e8540f980ea318447f79f4cba8813993ae2a6b/protos/camera/camera.proto#L255) [camera_status](https://github.com/mavlink/MAVSDK-Proto/blob/82e8540f980ea318447f79f4cba8813993ae2a6b/protos/camera/camera.proto#L349)

2. The [camera status](https://github.com/mavlink/MAVSDK-Proto/blob/82e8540f980ea318447f79f4cba8813993ae2a6b/protos/camera/camera.proto#L349) proto define. The camera status is packed in two mavlink message(**MAVLINK_MSG_ID_CAMERA_CAPTURE_STATUS** **MAVLINK_MSG_ID_STORAGE_INFORMATION**). The camera need to check the two [status value](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/plugins/camera/camera_impl.cpp#L1367). When implement the camera server side also have the same problem.

3. The camera parameter is not in the param list and need to be set by [**ParamServer**](https://github.com/mavlink/MAVSDK-Proto/blob/82e8540f980ea318447f79f4cba8813993ae2a6b/protos/param_server/param_server.proto#LL47C9-L47C27). 
4. But the value type is just [string type](https://github.com/mavlink/MAVSDK-Proto/blob/82e8540f980ea318447f79f4cba8813993ae2a6b/protos/param_server/param_server.proto#L98). I read some [camera define xml](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/plugins/camera/camera_definition_files/e90.xml#L87).The define type has various types. So I want to change the param_server.proto to support more custom define type.

```
enum ParamType {
    INT16_TYPE = 1;
    INT32_TYPE = 2;
   FLOAT_TYPE = 3;
  ....
    }
message ProvideParamCustomRequest {
    string name = 1; // Name of the parameter to provide
    ParamType type = 2; // In the param server convert to special type
    string value = 3; // Value the parameter should be set to
}
```
I have already test the param server use the e90.xml.
First add the param server in camera_server side.
```
    auto param_server = mavsdk::ParamServer(server_component);
    param_server.provide_param_custom("CAM_PHOTOQUAL", "1");
```
and the camera client will echo the following message:
`[05:31:12|Error] Param types don't match for CAM_PHOTORATIO`.

**Is this a good design?**

**Comment by julianoes** [comment]
1. I agree that this is duplication which is not so nice, however, we do auto-generation based on the proto files, and I'm not sure whether it would break it. Sometimes some duplication is ok because it makes it simpler and easier to read.
2. Yes, but my goal is to have an easy to use API so that the user doesn't have to care that there are two different messages which should just be an implementation detail.
3. Correct, you need to use a couple of plugins together for a camera server. You might even need the FtpServer plugin as well, once it exists (I'm working on it).
4. Hmm, no? There are int, float, and string (https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/param_server/param_server.proto#L11-L51) That should be enough, no?

**Comment by tbago** [comment]
the discussion will continue in the PR, so just close this issue.
